### ISSUE TITLE
tensorboard=2.0 cannot start in Anaconda Distribution 2019.03

### ISSUE THREAD

**Issue by mengxr** [AnacondaRecipes/tensorflow_recipes#20]
Tensorboard 2.0 (dynamically) requires setuptools>=41 while Anaconda Distribution 2019.03 bundles setuptools=40.8. Shall we explicitly declare dependency "setuptools>=41" in tensorboard recipe so users do not need to run into this error by default.

~~~
$ docker run -it continuumio/anaconda3:2019.03
# conda install tensorboard=2.0
# tensorboard -h

Traceback (most recent call last):
  File "/opt/conda/bin/tensorboard", line 10, in <module>
    sys.exit(run_main())
  File "/opt/conda/lib/python3.7/site-packages/tensorboard/main.py", line 58, in run_main
    default.get_plugins() + default.get_dynamic_plugins(),
  File "/opt/conda/lib/python3.7/site-packages/tensorboard/default.py", line 110, in get_dynamic_plugins
    for entry_point in pkg_resources.iter_entry_points('tensorboard_plugins')
  File "/opt/conda/lib/python3.7/site-packages/tensorboard/default.py", line 110, in <listcomp>
    for entry_point in pkg_resources.iter_entry_points('tensorboard_plugins')
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2410, in load
    self.require(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2433, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (setuptools 40.8.0 (/opt/conda/lib/python3.7/site-packages), Requirement.parse('setuptools>=41.0.0'))
~~~

**Comment by jjhelmus** [comment]
Adding a run time `setuptools >=41` requirement will enforce this requirement.  I'll add it to the recipe and create new packages.

**Comment by jjhelmus** [comment]
The existing `tensorboard` packages have this new requirement hotfixed in as well.

**Comment by mengxr** [comment]
Thanks @jjhelmus !
